name: unrepresentable_state

version: 0.0.1
description: >
  A set of objects that help developers implementing in a type driven
  fashion making illegal states unrepresentable.

repository: https://github.com/wltiii/unrepresentable_state
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equatable: ^2.0.5
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
